### ISSUE TITLE
fix structure 3bot

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/3bot#162]
# development_integration

## todo

- integrate all open branches to ```development_integration``` branch
- make documentation which includes specs for what we deliver
- define v 1.0.0 in issues milestone for our first release
- organize review cycles with kristof on what we already have and see what needs to be done
- all documentation is in 1 mdbook for the full web3gw

## make sure following concepts are used for the V code

- W3GW SAL (is a IMPERATIVE SAL)
    - SAL means = system abstraction layer 
    - V SAL to all functions of web3gw
    - W3GW 3SCRIPT
    - good documentation for W3GW SAL & W3GW 3ACTIONS (mdbook)
    - openrpc specs of all web3gw (generated using timur tool?)
    - in separate module
- TF SAL (is a IMPERATIVE SAL)
    - move things from crystallib to do with TF 
- W3GW SOLUTIONS
    - example deployments using V W3GW SAL
    - 3script driving the solutions (call solution with paramters)
    - in separate module
    - good documentation
- DECLARATIVE DSL (VDC = virtual datacenter)
   -  kristof to help
   - define V model 
   - 3 script to get to declarative model out of DSL
   - in separate module
- AUTONOMOUS IT 
   - code which maps between world reality and declarative models to make 3script actions for W3GW SAL
   - nothing today, but prepare the module & docs

**Comment by brandonpille** [comment]
I merged development into main. What happens with the development_integration branch now?

**Comment by brandonpille** [comment]
I have a question for the solutions. They should be defined on the V side and not on the go code? I'm just wondering why exactly? Because that means that people who are not interested in the V code will not be able to use that.

**Comment by brandonpille** [comment]
The w3gw SAL should be one class with all functions? No separating into clients?
