### ISSUE TITLE
rename to 3bot

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/3bot#171]
- name of repo = 3bot
- has 2 main sections
    - web3gateway
    - 3bot (v code making up the 3bot)
- license is apache 2, tftech

**Comment by brandonpille** [comment]
Is web3gw also good? It's shorter and looks nicer

**Comment by brandonpille** [comment]
Renamed the repository to 3bot. Github will redirect the fetches, pulls, pushes, etc to the new url but they do strongly recommend to change the remote of your clone of the repository:

```
git remote set-url origin git@github.com:threefoldtech/3bot.git
```

**Comment by rkhamis** [comment]
renamed and licensed
