### ISSUE TITLE
port ZOS primitives to V + spec

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/3bot#172]
## spec primitive types for ZOS deployment  

https://github.com/threefoldtech/zos/tree/main/pkg/gridtypes/zos

create V structs + deployment api (see zos)

most of work already done on https://github.com/threefoldtech/info_specs_grid3/tree/development/vlang/zos

## deployment in V

https://github.com/threefoldtech/info_specs_grid3/blob/development/vlang/testdeployment.v

**Comment by despiegk** [comment]
see also https://github.com/threefoldtech/zos/blob/main/docs/manual/api.md

**Comment by despiegk** [comment]
maybe a command line or so is needed, or binding something compliled in rust to allow communication with TFChain

idea is to have the structs as used in ZOS available with minimal change in V, also for querying info, document it properpy

**Comment by alichaddad** [comment]
A new go binary will be created to work with the v structs to handle the deployment, since the clients for relay and chain are already implemented in Golang.
The deploy script will use the v structs and prepare the necessary challenge hash and send it to the binary to communicate with the chain to create to the contract and then to the relay to create the deployment on the node.

**Comment by ashraffouda** [comment]
so far what is done types ported, we have a binary wrapped to do substrate requests creating/deleting .... contracts 
for rmbclient in v it has some issues we are working on fixing it right now

**Comment by ashraffouda** [comment]
rmb client fixed, deployments now works, so we will provided some examples how to deploy and also deployer needs to be updated to provide high level deployment deploy method to make it easy for the users to deploy stuff, also we need docs becuase this requires rmb-peer to be running and grid client binary to be exists

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/3bot/pull/192
